/*
Copyright ©  Olav Christian Botterli.

Dual licensed under the MIT or GPL Version 2 licenses.

Date: 30.08.2011, Norway.

http://www.webgrid.com
*/


#region Header

/*
Copyright ©  Olav Christian Botterli. 

Dual licensed under the MIT or GPL Version 2 licenses.

Date: 30.08.2011, Norway.

http://www.webgrid.com
*/
//
// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
//
//
// In order to sign your assembly you must specify a key to use. Refer to the
// Microsoft .NET Framework documentation for more information on assembly signing.
//
// Use the attributes below to control which key is used for signing.
//
// Notes:
//   (*) If no key is specified, the assembly is not signed.
//   (*) KeyName refers to a key that has been installed in the Crypto Service
//       Provider (CSP) on your machine. KeyFile refers to a file which contains
//       a key.
//   (*) If the KeyFile and the KeyName values are both specified, the
//       following processing occurs:
//       (1) If the KeyName can be found in the CSP, that key is used.
//       (2) If the KeyName does not exist and the KeyFile does exist, the key
//           in the KeyFile is installed into the CSP and used.
//   (*) In order to create a KeyFile, you can use the sn.exe (Strong ColumnId) utility.
//        When specifying the KeyFile, the location of the KeyFile should be
//        relative to the "project output directory". The location of the project output
//        directory is dependent on whether you are working with a local or web project.
//        For local projects, the project output directory is defined as
//       <Project Directory>\obj\<Configuration>. For example, if your KeyFile is
//       located in the project directory, you would specify the AssemblyKeyFile
//       attribute as [assembly: AssemblyKeyFile("..\\..\\mykey.snk")]
//        For web projects, the project output directory is defined as
//       %HOMEPATH%\VSWebCache\<Machine ColumnId>\<Project Directory>\obj\<Configuration>.
//   (*) Delay Signing is an advanced option - see the Microsoft .NET Framework
//       documentation for more information on this.
//
//[assembly:PermissionSet(SecurityAction., Name="Nothing")]

#endregion Header

using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Permissions;
using System.Web.UI;

[assembly: SecurityPermission(SecurityAction.RequestMinimum, UnmanagedCode = false)]
[assembly: AssemblyTitle("WebGrid ASP.NET DataGrid Component")]
[assembly: AssemblyDescription("WebGrid - plug and play DataGrid")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Olav Christian Botterli")]
[assembly: AssemblyProduct("WebGrid")]
[assembly: AssemblyCopyright("2011 Olav Christian Botterli. ")]
[assembly: AssemblyTrademark(" ")]
[assembly: AllowPartiallyTrustedCallers]
[assembly: Guid("915834D5-4D27-40de-8D65-2D3191537BC4")]
[assembly: TagPrefix("WebGrid", "WG")]


[assembly: WebResource("WebGrid.Resources.jquery-ui-black_tie.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-blitzer.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-cupertino.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-dark_hive.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-darkness.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-dot_luv.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-eggplant.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-excite_bike.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-flick.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-hot_sneaks.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-humanity.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-le_frog.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-lightness.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-mint_choc.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-overcast.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-pepper_grinder.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-redmond.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-smoothness.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-south_street.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-start.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-sunny.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-swanky_purse.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-trontastic.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-vader.css", "text/css", PerformSubstitution = true)]


[assembly: WebResource("WebGrid.Resources.WebGrid_JQueryUI.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("WebGrid.Resources.WebGrid_Misc.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.WebGrid_ColumnChanged.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.jquery-1.3.2.min.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.jquery-ui-1.7.2.custom.min.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.jquery.contextMenu.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.jquery-ui.selectmenu.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.jquery.meio.mask.min.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.jquery.jgrowl_minimized.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.jquery.colorbox-min.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.jquery.qtip-1.0.0-rc3.min.js", "text/javascript", PerformSubstitution = false)]
[assembly: WebResource("WebGrid.Resources.jquery-bookmark.js", "text/javascript", PerformSubstitution = false)]

[assembly: WebResource("WebGrid.Resources.noimage.gif", "image/gif")]

#region Jquery UI Images

[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonal-maze_20_6e4f1c_10x10.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonal-maze_40_000000_10x10.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-medium_20_d34d17_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-small_0_aaaaaa_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-small_25_c5ddfc_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-small_40_db4865_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-small_50_262626_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-small_50_93c3cd_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-small_50_ff3853_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-small_75_ccd232_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_15_0b3e6f_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_15_444444_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_18_b81900_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_20_666666_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_20_e69700_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_22_1484e6_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_26_2293f7_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_75_f3d8d8_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_8_333333_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_90_eeeeee_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diagonals-thick_95_ffdc2e_40x40.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diamond_10_4f4221_10x8.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diamond_20_372806_10x8.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diamond_25_675423_10x8.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diamond_25_d5ac5d_10x8.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diamond_8_261803_10x8.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_diamond_8_443113_10x8.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_dots-medium_30_0b58a2_4x4.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_dots-medium_80_ffff38_4x4.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_dots-small_20_333333_2x2.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_dots-small_30_a32d00_2x2.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_dots-small_35_35414f_2x2.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_dots-small_40_00498f_2x2.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_dots-small_65_a6a6a6_2x2.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_fine-grain_10_eceadf_60x60.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_fine-grain_10_f8f7f6_60x60.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_fine-grain_15_eceadf_60x60.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_fine-grain_15_f7f3de_60x60.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_fine-grain_15_ffffff_60x60.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_fine-grain_65_654b24_60x60.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_fine-grain_68_b83400_60x60.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_0_303030_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_0_333333_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_0_4c4c4c_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_0_aaaaaa_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_0_e69700_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_0_e6b900_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_0_eeeeee_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_10_000000_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_15_cd0a0a_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_30_cccccc_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_40_292929_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_50_5c5c5c_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_55_994d53_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_55_999999_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_55_c0402a_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_55_eeeeee_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_55_fafafa_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_55_fbec88_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_55_ffffff_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_65_ffffff_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_75_aaaaaa_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_75_ba9217_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_75_ddd4b0_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_75_ffffff_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_100_e4f1fb_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_100_f5f0e5_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_100_f6f6f6_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_100_f8f8f8_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_100_fdf5ce_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_15_5f391b_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_20_555555_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_25_cb842e_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_35_dddddd_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_40_0078a3_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_40_0a0a0a_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_40_111111_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_40_ffc73d_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_45_0078ae_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_50_3baae3_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_55_1c1c1c_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_55_f1fbe5_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_55_f8da4e_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_55_fbf5d0_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_55_fbf8ee_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_55_fbf9ee_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_55_fcf0ba_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_60_000000_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_60_eeeeee_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_65_ffffff_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_70_ede4d4_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_75_79c9ec_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_75_d0e5f5_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_75_dadada_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_75_e6e6e6_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_80_d7ebf9_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_85_dfeffc_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_95_fef1ec_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_100_ece8da_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_16_121212_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_20_111111_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_20_1c160d_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_25_333333_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_25_453326_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_30_3d3644_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_30_44372c_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_35_f6a828_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_45_817865_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_45_e14f1c_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_50_6eac2c_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_55_000000_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_55_5c9ccc_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_60_fece2f_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_70_ffdd57_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_75_2191c0_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_85_9fda58_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_90_fff9e5_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_95_f6ecd5_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_100_eeeeee_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_100_f2f5f7_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_100_f4f0ec_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_100_f5f3e5_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_100_f6f6f6_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_100_f9f9f9_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_100_fafaf4_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_15_459e00_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_15_888888_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_20_0972a5_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_30_285c00_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_40_aaaaaa_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_55_555555_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_65_fee4bd_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_70_000000_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_75_f5f5b5_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-hard_95_cccccc_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_100_dcd9de_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_100_deedf7_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_100_eae6ea_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_100_eeeeee_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_100_f6f6f6_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_100_f9f9f9_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_100_feeebd_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_15_cc0000_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_20_201913_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_20_619226_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_25_0073ea_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_25_30273a_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_25_67b021_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_25_ffef8f_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_33_003147_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_33_3a8104_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_35_222222_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_35_adadad_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_44_444444_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_45_5f5964_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_50_4eb305_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_50_aaaaaa_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_50_dddddd_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_60_4ca20b_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_60_dddddd_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_75_cccccc_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_75_ffe45c_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_80_eeeeee_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_95_ffedad_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-hard_100_eeeeee_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-hard_100_f5f8f9_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-hard_100_fcfdfd_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-hard_45_cd0a0a_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-hard_55_ffeb80_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-hard_75_999999_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-soft_100_f4f0ec_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-soft_10_201913_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-soft_10_285c00_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-soft_15_121212_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-soft_15_2b2922_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-soft_25_000000_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-soft_30_f58400_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-soft_30_ffffff_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_inset-soft_50_c9c9c9_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_loop_25_000000_21x21.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_white-lines_85_f7f7ba_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_000000_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_004276_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_00498f_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_0073ea_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_0078ae_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_056b93_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_070603_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_0a82eb_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_0b54d5_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_1f1f1f_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_217bc0_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_222222_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_228ef1_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_2694e8_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_2e83ff_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_3383bb_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_3572ac_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_3d3d3d_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_3d80b3_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_454545_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_469bdd_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_4b8e0b_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_4ca300_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_4eb305_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_5fa5e3_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_666666_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_6da8d5_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_70b2e1_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_72a7cf_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_72b42d_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_734d99_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_808080_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_847e71_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_888888_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_88a206_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_8c291d_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_8d78a5_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_8DC262_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_98d2fb_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_999999_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_9bcc60_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_9ccdfc_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_9fda58_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_a83300_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_a8a3ae_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_aaaaaa_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_add978_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_b83400_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_b8ec79_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_bbbbbb_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_bd7b00_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_c02669_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_c47a23_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_c98000_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_cb672b_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_cc0000_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_cccccc_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_cd0a0a_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_d19405_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_d8e7f3_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_e0fdff_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_e1e463_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_e3ddc9_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_e8e2b5_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_e9cd86_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_eb990f_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ebccce_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ed9f26_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ededed_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_eeeeee_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ef8c08_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_efec9f_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_f08000_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_f1fd86_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_f29a00_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_f2ec64_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_f35f07_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_f5e175_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_f7a50d_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_f9bd01_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_f9f2bd_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_fadc7a_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_fbc856_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_fbdb93_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_fcd113_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_fcdd4a_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ff0084_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ff7519_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ffcf29_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ffd27a_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ffe180_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ffeb33_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_ffffff_256x240.png", "image/png")]

#endregion

/*
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_0_aaaaaa_40x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_75_ffffff_40x100.png", "image/png")]

[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_55_fbf9ee_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_65_ffffff_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_75_dadada_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_75_e6e6e6_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_glass_95_fef1ec_1x400.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_highlight-soft_75_cccccc_1x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_gloss-wave_55_000000_500x100.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-bg_flat_0_eeeeee_40x100.png", "image/png")]




[assembly: WebResource("WebGrid.Resources.images.ui-icons_222222_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_2e83ff_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_454545_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_888888_256x240.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.ui-icons_cd0a0a_256x240.png", "image/png")]
 */
[assembly: WebResource("WebGrid.Resources.images.loading.gif", "image/gif")]
[assembly: WebResource("WebGrid.Resources.images.controls.png", "image/png")]
[assembly: WebResource("WebGrid.Resources.images.calendar.gif", "image/gif")]
[assembly: WebResource("WebGrid.Resources.images.exit.gif", "image/gif")]
[assembly: WebResource("WebGrid.Resources.images.export.gif", "image/gif")]
[assembly: WebResource("WebGrid.Resources.images.help.gif", "image/gif")]
[assembly: WebResource("WebGrid.Resources.images.print.gif", "image/gif")]
[assembly: WebResource("WebGrid.Resources.images.refresh.gif", "image/gif")]
[assembly: WebResource("WebGrid.Resources.images.transparent.gif", "image/gif")]


[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("3.3.1.*")]
[assembly: AssemblyDelaySign(false)]

//[assembly : AssemblyKeyFileAttribute(@"..\..\WebGrid.snk")]
[assembly: AssemblyKeyName("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]