/*
Copyright ©  Olav Christian Botterli.

Dual licensed under the MIT or GPL Version 2 licenses.

Date: 30.08.2011, Norway.

http://www.webgrid.com
*/


#region Header

/*
Copyright ©  Olav Christian Botterli. 

Dual licensed under the MIT or GPL Version 2 licenses.

Date: 30.08.2011, Norway.

http://www.webgrid.com
*/

#endregion Header

using System;
using System.ComponentModel;

namespace WebGrid
{
    /// <summary>
    /// Disable Javascript resources being generated by WebGrid.
    /// </summary>
    public  class ScriptSettings
    {
        #region Properties



        /// <summary>
        /// </summary>
        /// <value><c>true</c> if [allow cancel]; otherwise, <c>false</c>.</value>
        [Bindable(true), Category("Behavior"), DefaultValue(true), Description(
            @"Sets or gets if WebGrid should use Ajax Loader. Default is true.")]
        public bool DisableAjaxLoader { get; set; }
        /// <summary>
        /// Disable JGrowl - a Jquery Notification plugin. http://plugins.jquery.com/project/jGrowl
        /// </summary>
        public bool DisableClientNotification
        {
            get;
            set;
        }

        /// <summary>
        /// Disable ContextMenu
        /// </summary>
        /// <remarks>
        /// </remarks>
        public bool DisableContextMenu
        {
            get; set;
        }

        /// <summary>
        /// Disable JQuery UI hover effect on buttons.
        /// </summary>
        /// <remarks>
        /// </remarks>
        public bool DisableHoverButtons
        {
            get; set;
        }

        ///<summary>
        /// Disable meioMask - a jQuery mask plugin. http://plugins.jquery.com/project/meiomask
        ///</summary>
        public bool DisableInputMask
        {
            get; set;
        }

        /// <summary>
        /// Disable JQuery (1.3.2) resource scripts
        /// </summary>
        /// <remarks>
        /// </remarks>
        public bool DisableJQuery
        {
            get; set;
        }

        /// <summary>
        /// Disable JQuery UI (1.7.2)
        /// </summary>
        public bool DisableJQueryUI
        {
            get; set;
        }

        /// <summary>
        /// Disable ColorBox  resource scripts
        /// </summary>
        /// <remarks>
        /// </remarks>
        public bool DisablePopupExtender
        {
            get; set;
        }

        /// <summary>
        /// Disable QTip (1.0.0rc3) resource scripts
        /// </summary>
        public bool DisableToolTip
        {
            get; set;
        }

        /// <summary>
        /// Disable JQuery (1.3.2) resource scripts
        /// </summary>
        /// <remarks>
        /// </remarks>
        public bool DisableWebGridClientObject
        {
            get; set;
        }

        ///<summary>
        /// Start index for controls to be register in page header. Default is 0.
        ///</summary>
        /// <remarks>
        /// This property is useful if you want to register scripts before WebGrid.
        /// </remarks>
        public int HeaderStartIndex
        {
            get; set;
        }
        /// <summary>
        /// Disable JQuery UI Select Menu
        /// </summary>
        /// <remarks>
        /// </remarks>
        public bool DisableSelectMenu
        {
            get;
            set;
        }
        ///<summary>
        /// Disable bookmark
        ///</summary>
        /// <remarks>
        /// This property is useful.
        /// </remarks>
        public bool DisableBookmark
        {
            get;
            set;
        }

        #endregion Properties

        #region Methods

        /// <summary>
        /// Returns a <see cref="T:System.String"/> that represents the current <see cref="T:System.Object"/>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"/> that represents the current <see cref="T:System.Object"/>.
        /// </returns>
        /// <filterpriority>2</filterpriority>
        public override string ToString()
        {
            return "No design support";
        }

        #endregion Methods
    }
}