//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrid.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebGrid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;, sticky: {0}.
        /// </summary>
        internal static string DesignRender_Render____sticky___0_ {
            get {
                return ResourceManager.GetString("DesignRender_Render____sticky___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , life: {0}.
        /// </summary>
        internal static string DesignRender_Render___life___0_ {
            get {
                return ResourceManager.GetString("DesignRender_Render___life___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to push rows down 1..
        /// </summary>
        internal static string FailedToPushRowsDown1 {
            get {
                return ResourceManager.GetString("FailedToPushRowsDown1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to push rows down 2..
        /// </summary>
        internal static string FailedToPushRowsDown2 {
            get {
                return ResourceManager.GetString("FailedToPushRowsDown2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of parameters for PushRowDown method, excepted 7 arguments was {0}..
        /// </summary>
        internal static string InvalidNumberOfParametersForPushRowDownMethodExcepted7ArgumentsWas0 {
            get {
                return ResourceManager.GetString("InvalidNumberOfParametersForPushRowDownMethodExcepted7ArgumentsWas0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse orginal values from &apos;{0}&apos; column (Value:&apos;{1}&apos;)..
        /// </summary>
        internal static string UnableToParseOrginalValuesFrom0ColumnValue1 {
            get {
                return ResourceManager.GetString("UnableToParseOrginalValuesFrom0ColumnValue1", resourceCulture);
            }
        }
    }
}
